"""add user_id to monitors

Revision ID: a0dd4ade47fe
Revises: dfa5a3c17c09
Create Date: 2026-09-24 11:57:45.454285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dd4ade47fe'
down_revision: Union[str, Sequence[str], None] = 'dfa5a3c17c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'monitors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'monitors', type_='foreignkey')
    op.drop_column('monitors', 'user_id')
    # ### end Alembic commands ###
